openapi: 3.0.0
info:
  title: AWS Workshop API
  version: 1.0.0
servers:
  - url: https://nh22z5ti2i.execute-api.eu-north-1.amazonaws.com/prod
    description: Product Service API (AWS Gateway)
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductList
      responses:
        "200":
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /products/{productId}:
    get:
      summary: Get single product by id
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
            example: "1"
      responses:
        "200":
          description: A product object
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Product"
        "404":
          description: A special object with error information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product not found"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "Product 1"
        description:
          type: string
          example: "Description of Product 1"
        price:
          type: number
          format: float
          example: 100.15
