openapi: 3.0.0
info:
  title: Product Service Api
  version: 1.0.0
servers:
  - url: https://mfdlk5m2da.execute-api.eu-north-1.amazonaws.com
    description: Product Service API (AWS Gateway)
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductList
      responses:
        "200":
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          $ref: "#/components/responses/InternalError"
    post:
      summary: Create new product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: A JSON array of products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Invalid request data
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                example:
                  statusCode: 400
                  message: "Invalid request data"
        "500":
          $ref: "#/components/responses/InternalError"
  /products/{productId}:
    get:
      summary: Get single product by id
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
            example: "380c28a6-f905-4dc8-9a7e-fd47118c95e3"
      responses:
        "200":
          description: A product object
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Product"
        "404":
          description: Invalid resource url
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                example:
                  statusCode: 404
                  message: "Product not found"
        "500":
          $ref: "#/components/responses/InternalError"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "276ee84f-8401-4af5-92a2-d5c0eeb9b191"
        title:
          type: string
          example: "Product 1"
        description:
          type: string
          example: "Description of Product 1"
        price:
          type: number
          format: float
          example: 100.15
        count:
          type: integer
          example: 1
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: number
        message:
          type: string
      example:
        statusCode: 500
        message: "Unknown processing error"
  responses:
    InternalError:
      description: Unknown server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
